// <auto-generated />
namespace PointOfSales.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class six3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(six3));
        
        string IMigrationMetadata.Id
        {
            get { return "201603221933406_six3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
